'''
Sends frames from a live camera to the Eucalyptus API.
Prints responses.
'''
import time
import logging
from pathlib import Path

from senseye_api_client import SenseyeApiClient


# Silence debug logs generated by senseye_cameras
logging.getLogger('senseye_cameras').setLevel(logging.WARNING)

CAMERA_ID = 0
CAMERA_TYPE = 'usb'     # generic usb camera
# CAMERA_TYPE = 'ueye'    # IDS ueye camera
# CAMERA_TYPE = 'pylon'   # Basler pylon camera

api = SenseyeApiClient(config=(Path(__file__).parent / 'config.yml'))
response_number = 0
start_time = time.time()

for response in api.stream_eye_metrics(CAMERA_TYPE, CAMERA_ID):
    response_number += 1
    fps = response_number / (time.time() - start_time)
    print(f"Receiving response {response_number}, overall fps: {fps}, contents: {response}")
